on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  hello_world:
    run-on: ubuntu-latest
    steps:
      - name: "Echo Basic Information"
        run: echo "Hello Test"